# Generated by Django 4.2.2 on 2023-06-16 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="first_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
